name: "Nix build"
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - run: nix flake check -L
