---
name: "Luarocks release"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
      - name: Fail if changelog entry does not exist
        run: grep -q "${{ github.ref_name }}" CHANGELOG.md
      - name: GitHub release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          allowUpdates: true
